Repository FalkenDev/microblog, pull requests merged in 2023-11, with the labels that each got.

#2 Initial start of the project
  .vscode/settings.json
  CHANGELOG.md
  boot.sh
  docker/Dockerfile_prod
  gitConfigs/commit-conventions.txt
  microblog.py
Labels: enhancement

#3 Created Python CI for tests (Actions)
  .github/workflows/python-ci.yml
Labels: test

#5 Added template for pull requests
  .github/pull_request_template.md
Labels: documentation, enhancement

#4 ci: Fixed Python CI Tests
  .github/workflows/python-ci.yml
  README.md
Labels: test, bugfix

#6 docs: Updated Changelog with the latest features and fixes
  CHANGELOG.md
Labels: documentation

#8 cd: Changed to use release tag name
  .github/workflows/docker-publish.yml
Labels: bugfix

#10 cd: Added docker image publish for test and prod
  .github/workflows/docker-publish.yml
Labels: bugfix

#11 docs: Changelog updated with new release 0.1.0
  CHANGELOG.md
Labels: documentation

#13 docs: Changelog updated to reflect the new release [0.2.0] and [1.0.0]
  CHANGELOG.md
Labels: documentation

#14 Development to Master branch (Kmom01)
  .github/pull_request_template.md
  .github/workflows/docker-publish.yml
  .github/workflows/python-ci.yml
  .vscode/settings.json
  CHANGELOG.md
  Makefile
  README.md
  app/main/routes.py
  app/models.py
  app/templates/user.html
  boot.sh
  docker-compose.yml
  docker/Dockerfile_prod
  docker/Dockerfile_test
  gitConfigs/commit-conventions.txt
  microblog.py
  migrations/versions/e96cbeefa9ae_followers.py
  run_tests.sh
  tests/unit/models/test_followers.py
Labels: documentation, enhancement, test

#15 Dbwebb-fork-sync-02
  ansible/10-first-minutes.yml
  ansible/README.md
  ansible/ansible.cfg
  ansible/gather_instances.yml
  ansible/group_vars/all.yml
  ansible/group_vars/devops.yml
  ansible/provision_instances.yml
  ansible/roles/10-first-minutes/files/apt_periodic
  ansible/roles/10-first-minutes/files/apt_periodic_50
  ansible/roles/10-first-minutes/handlers/main.yml
  ansible/roles/10-first-minutes/tasks/main.yml
  ansible/roles/10-first-minutes/vars/main.yml
  ansible/roles/gather_instances/tasks/main.yml
  ansible/roles/provision_instances/meta/main.yml
  ansible/roles/provision_instances/tasks/add_vms_as_hosts.yml
  ansible/roles/provision_instances/tasks/create_instance.yml
  ansible/roles/provision_instances/tasks/main.yml
  ansible/roles/provision_instances/tasks/vnet.yml
  ansible/roles/provision_instances/vars/main.yml
  ansible/roles/security_groups/defaults/main.yml
  ansible/roles/security_groups/tasks/main.yml
  ansible/roles/security_groups/vars/main.yml
  ansible/roles/terminate_instances/tasks/main.yml
  ansible/roles/terminate_instances/tasks/remove_instance.yml
  ansible/roles/terminate_instances/tasks/vnet.yml
  ansible/roles/terminate_instances/vars/main.yml
  ansible/site.yml
  ansible/terminate_instances.yml
Labels: enhancement, bugfix, dbwebb

#16 Azure pub keys
  ansible/roles/10-first-minutes/files/azure_james.pub
  ansible/roles/10-first-minutes/files/azure_joel.pub
  ansible/roles/10-first-minutes/files/azure_kasper.pub
Labels: enhancement

#17 Build: SSH authorized key update
  ansible/group_vars/devops.yml
  ansible/group_vars/local.yml
  ansible/roles/10-first-minutes/tasks/main.yml
  ansible/roles/10-first-minutes/vars/main.yml
Labels: enhancement, bugfix, build

#18 Build: Ansible Docker MySQL
  ansible/mysql-docker.yml
  ansible/roles/docker-install/tasks/main.yml
  ansible/roles/mysql-docker/tasks/main.yml
Labels: enhancement, build

#20 Provision Update
  ansible/roles/provision_instances/vars/main.yml
Labels: enhancement, build

#21 Build: Ansible docker appservers
  .gitignore
  Makefile
  ansible/appserver.yml
  ansible/group_vars/all.yml
  ansible/roles/appserver/tasks/main.yml
  ansible/roles/docker-install/tasks/main.yml
  ansible/roles/mysql-docker/tasks/main.yml
Labels: enhancement, build

#23 FIX: Gitignore fix
  .gitignore
  Makefile
  ansible/group_vars/all.yml
Labels: bugfix

#22 Docs: Updated Changelog to reflect the new builds and fixes
  CHANGELOG.md
Labels: documentation

#19 Build: Load balancer ansible
  ansible/load_balancer.yml
  ansible/roles/appserver/tasks/main.yml
  ansible/roles/load_balancer/tasks/main.yml
  ansible/roles/load_balancer/tasks/templates/load-balancer.conf.j2
  ansible/roles/load_balancer/tasks/templates/nginx.conf.j2
  ansible/roles/load_balancer/vars/main.yml
Labels: bug, enhancement, build

#24 Continous deployment
  .github/workflows/deploy.yml
  ansible/deploy.yml
  ansible/hosts
  ansible/roles/provision_instances/tasks/create_instance.yml
  ansible/roles/provision_instances/vars/main.yml
Labels: bug

#25 Db subdomain
  ansible/hosts
  ansible/roles/provision_instances/tasks/create_instance.yml
Labels: build

#26 App version route
  .github/workflows/docker-publish.yml
  ansible/deploy.yml
  app/main/routes.py
Labels: enhancement, build

#27 Domain chane in host
  ansible/group_vars/all.yml
  ansible/hosts
Labels: bugfix

#28 Added ssh key
  .github/workflows/deploy.yml
Labels: bugfix

#29 Added workflow call to wait docker before deploy
  .github/workflows/deploy.yml
  .github/workflows/docker-publish.yml
Labels: bugfix

#30 Added inherit secret
  .github/workflows/deploy.yml
  .github/workflows/docker-publish.yml
Labels: bugfix

#31 Fixed enviroment route version
  app/main/routes.py
Labels: bugfix

#32 Rename DOCKER_TAG to APP_VERSION
  .github/workflows/docker-publish.yml
Labels: bugfix

#33 Trying to fix app version route
  .github/workflows/docker-publish.yml
  app/main/routes.py
Labels: bugfix

#34 Test code
  app/main/routes.py
Labels: bug

#35 Enviroment version
  app/main/routes.py
  docker/Dockerfile_prod
Labels: bugfix

#36 Push development branch to master [Kmom02]
  .github/workflows/deploy.yml
  .github/workflows/docker-publish.yml
  CHANGELOG.md
  Makefile
  ansible/10-first-minutes.yml
  ansible/README.md
  ansible/ansible.cfg
  ansible/appserver.yml
  ansible/deploy.yml
  ansible/gather_instances.yml
  ansible/group_vars/all.yml
  ansible/group_vars/devops.yml
  ansible/group_vars/local.yml
  ansible/hosts
  ansible/load_balancer.yml
  ansible/mysql-docker.yml
  ansible/provision_instances.yml
  ansible/roles/10-first-minutes/files/apt_periodic
  ansible/roles/10-first-minutes/files/apt_periodic_50
  ansible/roles/10-first-minutes/files/azure_james.pub
  ansible/roles/10-first-minutes/files/azure_joel.pub
  ansible/roles/10-first-minutes/files/azure_kasper.pub
  ansible/roles/10-first-minutes/handlers/main.yml
  ansible/roles/10-first-minutes/tasks/main.yml
  ansible/roles/10-first-minutes/vars/main.yml
  ansible/roles/appserver/tasks/main.yml
  ansible/roles/docker-install/tasks/main.yml
  ansible/roles/gather_instances/tasks/main.yml
  ansible/roles/load_balancer/tasks/main.yml
  ansible/roles/load_balancer/tasks/templates/load-balancer.conf.j2
  ansible/roles/load_balancer/tasks/templates/nginx.conf.j2
  ansible/roles/load_balancer/vars/main.yml
  ansible/roles/mysql-docker/tasks/main.yml
  ansible/roles/provision_instances/meta/main.yml
  ansible/roles/provision_instances/tasks/add_vms_as_hosts.yml
  ansible/roles/provision_instances/tasks/create_instance.yml
  ansible/roles/provision_instances/tasks/main.yml
  ansible/roles/provision_instances/tasks/vnet.yml
  ansible/roles/provision_instances/vars/main.yml
  ansible/roles/security_groups/defaults/main.yml
  ansible/roles/security_groups/tasks/main.yml
  ansible/roles/security_groups/vars/main.yml
  ansible/roles/terminate_instances/tasks/main.yml
  ansible/roles/terminate_instances/tasks/remove_instance.yml
  ansible/roles/terminate_instances/tasks/vnet.yml
  ansible/roles/terminate_instances/vars/main.yml
  ansible/site.yml
  ansible/terminate_instances.yml
  app/main/routes.py
  docker/Dockerfile_prod
Labels: enhancement

#38 tests: Added Bandit test to find possible security holes in the Python code
  .github/workflows/BTD-ci.yml
  .github/workflows/docker-publish.yml
  Makefile
  requirements/test.txt
Labels: test

#40 test/ci: Added Dockle test
  .github/workflows/BTD-ci.yml
  .github/workflows/docker-publish.yml
  Makefile
  docker/Dockerfile_prod
Labels: test, build

#41 Trivy testing and security fixes
  .github/workflows/BTD-ci.yml
  Makefile
  docker/Dockerfile_prod
  requirements.txt
  requirements/prod.txt
  requirements/test.txt
Labels: bugfix, build

#42 Fix trivy issues
  docker/Dockerfile_prod
  requirements/prod.txt
  requirements/test.txt
Labels: bugfix

#43 fix: Update trivy-test make
  Makefile
Labels: test, bugfix

#39 Updated Security groups
  ansible/provision_instances.yml
  ansible/roles/security_groups/vars/main.yml
Labels: enhancement, build, securityfix

#45 Fixed vulnerability warnings from zap
  ansible/roles/appserver/tasks/main.yml
  ansible/roles/load_balancer/tasks/templates/load-balancer.conf.j2
Labels: test, bugfix, securityfix

#47 Bugfix security groups
  ansible/provision_instances.yml
  ansible/roles/security_groups/tasks/main.yml
  ansible/roles/security_groups/vars/main.yml
Labels: bugfix, build, securityfix

#48 Ansible fix
  ansible/10-first-minutes.yml
  ansible/gather_instances.yml
  ansible/roles/10-first-minutes/files/sshd_config.j2
  ansible/roles/10-first-minutes/handlers/main.yml
  ansible/roles/10-first-minutes/tasks/main.yml
  ansible/terminate_instances.yml
Labels: bugfix, build

#50 Development branch to Master
  .github/workflows/BTD-ci.yml
  .github/workflows/docker-publish.yml
  CHANGELOG.md
  Makefile
  ansible/10-first-minutes.yml
  ansible/gather_instances.yml
  ansible/provision_instances.yml
  ansible/roles/10-first-minutes/files/sshd_config.j2
  ansible/roles/10-first-minutes/handlers/main.yml
  ansible/roles/10-first-minutes/tasks/main.yml
  ansible/roles/appserver/tasks/main.yml
  ansible/roles/load_balancer/tasks/templates/load-balancer.conf.j2
  ansible/roles/security_groups/tasks/main.yml
  ansible/roles/security_groups/vars/main.yml
  ansible/terminate_instances.yml
  docker/Dockerfile_prod
  requirements.txt
  requirements/prod.txt
  requirements/test.txt
Labels: enhancement

#51 Load balancer nginx exporter
  ansible/load_balancer.yml
  ansible/roles/load_balancer/tasks/main.yml
  ansible/roles/load_balancer/tasks/templates/load-balancer.conf.j2
Labels: enhancement, build

#52 Prometheus Flask export
  boot.sh
  docker/Dockerfile_prod
  gunicorn_config.py
  requirements/prod.txt
Labels: enhancement, build

#53 Ansible monitoring
  ansible/monitoring.yml
  ansible/roles/load_balancer/tasks/templates/load-balancer.conf.j2
  ansible/roles/monitoring/files/alertmanager.yml
  ansible/roles/monitoring/files/docker-compose.yml
  ansible/roles/monitoring/files/grafana.ini
  ansible/roles/monitoring/files/prometheus.yml
  ansible/roles/monitoring/files/rules.yml
  ansible/roles/monitoring/tasks/main.yml
  ansible/roles/monitoring/vars/main.yml
  ansible/roles/provision_instances/vars/main.yml
  ansible/roles/security_groups/vars/main.yml
Labels: enhancement, build

#54 Gunicorn Prometheus Metrics fix to app
  app/__init__.py
Labels: enhancement, bugfix, build

#55 Added port for exporter in load balancer
  ansible/roles/security_groups/vars/main.yml
Labels: bugfix, build

#56 fix: Adding the PROMETHEUS_MULTIPROC_DIR to the test dockerfile
  docker/Dockerfile_test
Labels: bugfix, build

#57 fix: Fixing pytest unit
  .github/workflows/python-ci.yml
  requirements/test.txt
Labels: test, bugfix

#58 GunicornInternalPrometheusMetrics fix
  app/__init__.py
  gunicorn_config.py
  requirements/test.txt
Labels: bugfix

#59 build: Add node exporter to database vm
  ansible/roles/monitoring/files/prometheus.yml
  ansible/roles/mysql-docker/tasks/main.yml
Labels: enhancement, build

#63 Development to Master merge
  .github/workflows/python-ci.yml
  CHANGELOG.md
  ansible/load_balancer.yml
  ansible/monitoring.yml
  ansible/roles/load_balancer/tasks/main.yml
  ansible/roles/load_balancer/tasks/templates/load-balancer.conf.j2
  ansible/roles/monitoring/files/alertmanager.yml
  ansible/roles/monitoring/files/docker-compose.yml
  ansible/roles/monitoring/files/flask_dash.json
  ansible/roles/monitoring/files/grafana.ini
  ansible/roles/monitoring/files/nginx_dash.json
  ansible/roles/monitoring/files/prometheus.yml
  ansible/roles/monitoring/files/rules.yml
  ansible/roles/monitoring/tasks/main.yml
  ansible/roles/monitoring/vars/main.yml
  ansible/roles/mysql-docker/tasks/main.yml
  ansible/roles/provision_instances/vars/main.yml
  ansible/roles/security_groups/vars/main.yml
  app/__init__.py
  boot.sh
  docker/Dockerfile_prod
  docker/Dockerfile_test
  gunicorn_config.py
  requirements/prod.txt
  requirements/test.txt
Labels: enhancement
