Repository FalkenDev/microblog, pull requests merged in 2023-12, with the labels that each got.

#64 fix: Added task to update requests_toolbelt & urllib3
  ansible/roles/load_balancer/tasks/main.yml
Labels: bugfix

#65 Doppler
  .github/workflows/deploy.yml
  ansible/group_vars/all.yml
  ansible/group_vars/devops.yml
  ansible/roles/10-first-minutes/tasks/main.yml
  ansible/roles/10-first-minutes/vars/main.yml
Labels: enhancement, build

#66 Doppler update
  CHANGELOG.md
  DOPPLER.md
  doppler.yaml
  img/addIntegration.png
  img/dopplerGithub.png
  img/dopplerPricing.png
  img/dopplerProjects.png
  img/dopplerSecrets.png
  img/dopplerServiceToken.png
  img/dopplerWorkflow.png
  img/integrations.png
Labels: documentation, enhancement, build

#67 fix: doppler images
  img/dopplerServiceToken.png
  img/dopplerWorkflow.png
Labels: documentation, bugfix

#68 Development to Master Merge
  .github/workflows/deploy.yml
  CHANGELOG.md
  DOPPLER.md
  ansible/group_vars/all.yml
  ansible/group_vars/devops.yml
  ansible/roles/10-first-minutes/tasks/main.yml
  ansible/roles/10-first-minutes/vars/main.yml
  ansible/roles/load_balancer/tasks/main.yml
  doppler.yaml
  img/addIntegration.png
  img/dopplerGithub.png
  img/dopplerPricing.png
  img/dopplerProjects.png
  img/dopplerSecrets.png
  img/dopplerServiceToken.png
  img/dopplerWorkflow.png
  img/integrations.png
Labels: enhancement

#69 Kubernetes kasper
  kubernetes/kasper/demo/01-deployment.yml
  kubernetes/kasper/demo/02-service.yml
  kubernetes/kasper/demo/03-ingress.yml
  kubernetes/kasper/demo/04-issuer-staging.yml
  kubernetes/kasper/demo/05-issuer-prod.yml
  kubernetes/kasper/microblog/01-deployment.yml
  kubernetes/kasper/microblog/02-service.yml
  kubernetes/kasper/microblog/03-ingress.yml
  kubernetes/kasper/microblog/04-issuer-staging.yml
  kubernetes/kasper/microblog/05-issuer-prod.yml
  kubernetes/kasper/mysql/mysql-deployment.yml
  kubernetes/kasper/mysql/mysql-pv.yml
  kubernetes/kasper/mysql/mysql-secrets.yml
Labels: build
